name: Autograding Tests
'on': {}
permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: pip install pytest bs4 cssutils pytest-json-report

    - name: Run pytest
      id: pytest-run
      continue-on-error: true  # Akkor is folytatja a workflow-t, ha egy teszt elbukik
      run: pytest --tb=short --disable-warnings --json-report --json-report-file=results.json || true

    - name: Process results for autograding
      id: process-results
      run: |
        import json
        import os

        total_score = 0
        max_score = 40

        try:
            # JSON fájl beolvasása
            with open("results.json") as f:
                data = json.load(f)

            # Ha vannak tesztek, dolgozzuk fel az eredményeket
            if isinstance(data, list):
                for test in data:
                    if test.get("status") == "passed":
                        total_score += test.get("points", 0)

            # Ha a pontszám meghaladja a maximumot, vágjuk le
            total_score = min(total_score, max_score)

        except (FileNotFoundError, json.JSONDecodeError):
            print("No valid results.json found, setting score to 0.")

        print(f"Final Score: {total_score}/{max_score}")

        # Kiírjuk az összpontszámot GitHub Actions környezeti változóként
        with open(os.getenv('GITHUB_ENV'), 'a') as f:
            f.write(f"{total_score}/{max_score}\n")

      shell: python

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TOTAL_SCORE: "${{ env.TOTAL_SCORE }}"
      with:
        runners: pytest-run
